// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FileRepository is an autogenerated mock type for the FileRepository type
type FileRepository struct {
	mock.Mock
}

// Upload provides a mock function with given fields: ctx, file, filename
func (_m *FileRepository) Upload(ctx context.Context, file io.Reader, filename string) (string, error) {
	ret := _m.Called(ctx, file, filename)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) string); ok {
		r0 = rf(ctx, file, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = rf(ctx, file, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
