// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	domain "github.com/rknizzle/rkmesh/domain"

	mock "github.com/stretchr/testify/mock"
)

// ModelService is an autogenerated mock type for the ModelService type
type ModelService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ModelService) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUserModels provides a mock function with given fields: ctx, userID
func (_m *ModelService) GetAllUserModels(ctx context.Context, userID int64) ([]domain.Model, error) {
	ret := _m.Called(ctx, userID)

	var r0 []domain.Model
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Model); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Model)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ModelService) GetByID(ctx context.Context, id int64) (domain.Model, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Model
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Model); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Model)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *ModelService) GetByName(ctx context.Context, name string) (domain.Model, error) {
	ret := _m.Called(ctx, name)

	var r0 domain.Model
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Model); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Model)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *ModelService) Store(_a0 context.Context, _a1 *domain.Model, _a2 io.Reader, _a3 string, _a4 int64) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Model, io.Reader, string, int64) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
